#!/bin/bash

BASE_DIR=$HOME/.local/share/cenv
ENV=$1
ENV_DIR=$BASE_DIR/$ENV

if [ -z "$ENV" ]; then
    echo "Usage: cenv <envname>"
    exit 1
fi

mkdir -p $ENV_DIR

export CENV=$ENV_DIR
export VIRTUAL_ENV=$ENV
export PATH=$ENV_DIR/bin:$PATH
export LD_LIBRARY_PATH=$ENV_DIR/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$ENV_DIR/lib/pkgconfig:$PKG_CONFIG_PATH
export GI_TYPELIB_PATH=$ENV_DIR/lib/girepository-1.0:$GI_TYPELIB_PATH

bash
