#!/usr/bin/env python
# Copyright (C) 2012 Matthias Vogelgesang
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

import sys
import os
import urllib2
import json
import argparse


def store_gist(args):
    data = urllib2.urlopen('https://api.github.com/gists/%i' % args.gist).read()
    gist = json.loads(data)
    files = gist['files']

    for f in files.keys():
        if os.path.exists(f) and not args.force:
            print("Ignoring `%s'" % f)
        else:
            open(f, 'w').write(files[f]['content'])


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--force',
                        action='store_true',
                        help='Overwrite existing files')
    parser.add_argument('gist',
                        type=int,
                        help='Gist id')

    args = parser.parse_args()
    store_gist(args)
