#!/bin/bash

export LANG=""

WIFI_STATUS=$(nmcli -t -f WIFI nm wifi)
WIRED_STATUS=$(nmcli -t -f WWAN nm wwan)

# NEW_MAIL_ICON="/usr/share/icons/gnome/32x32/status/mail-unread.png"
# NEW_MAIL_SUMMARY="New mail"

if [ "$WIFI_STATUS" == "enabled" ] || [ "$WIRED_STATUS" == "enabled" ]; then
    mbsync gmail
fi

# notify-send --urgency=low --icon=$NEW_MAIL_ICON "$NEW_MAIL_SUMMARY" "There is a new mail"
